apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-01
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app-01
  template:
    metadata:
      labels:
        app: flask-app-01
    spec:
      imagePullSecrets:
      - name: dockerhub-creds
      containers:
      - name: flask-app-01
        image: fullstackmalinda/flask-app-01:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: flask-app-01
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30036

